In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [18]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [19]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [20]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [21]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [26]:
#X.tolist()

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [28]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [30]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [31]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)


Epoch 1/100
8000/8000 [==============================] - 6s - loss: 0.4943 - acc: 0.7950     
Epoch 2/100
8000/8000 [==============================] - 3s - loss: 0.4290 - acc: 0.7960     
Epoch 3/100
8000/8000 [==============================] - 2s - loss: 0.4238 - acc: 0.7960     
Epoch 4/100
8000/8000 [==============================] - 2s - loss: 0.4197 - acc: 0.8127     
Epoch 5/100
8000/8000 [==============================] - 3s - loss: 0.4168 - acc: 0.8250     
Epoch 6/100
8000/8000 [==============================] - 2s - loss: 0.4144 - acc: 0.8297     
Epoch 7/100
8000/8000 [==============================] - 3s - loss: 0.4128 - acc: 0.8307     
Epoch 8/100
8000/8000 [==============================] - 2s - loss: 0.4111 - acc: 0.8315     
Epoch 9/100
8000/8000 [==============================] - 2s - loss: 0.4103 - acc: 0.8330     
Epoch 10/100
8000/8000 [==============================] - 2s - loss: 0.4087 - acc: 0.8350     
Epoch 11/100
8000/8000 [==============================] - 2

In [32]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [33]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [34]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [35]:
cm

array([[1553,   42],
       [ 276,  129]])

In [36]:
(1553 + 129)/2000

0.841

In [37]:
#new_costumer : france,600,male,40,3,60000,2,yes,yes,50000
new_pred = classifier.predict(sc.fit_transform([[0.0,0,600,1,40,3,60000,2,1,1,50000]]))
new_pred = (new_pred > 0.5)

In [38]:
new_pred

array([[False]])